#!/usr/bin/env bash
#
# OpenHands Quality Gate
# Auto-generated by ai-dev-toolkit — DO NOT EDIT MANUALLY unless you understand the implications.
#
# This script is invoked as a post-hook after OpenHands task execution.
# It performs safety checks, runs project tests if available, and ensures
# no forbidden actions were performed.
#
# Requirements:
#   - Bash only (no external dependencies to install)
#   - Must exit non-zero on detected risks
#   - Must NOT auto git commit or git push

set -uo pipefail

###############################################################################
# Configuration — override via environment if needed
###############################################################################
FORBIDDEN_FILE_PATTERNS=(
  ".env"
  "*.pem"
  "*.key"
  "id_rsa"
  "*secret*"
  "*credential*"
)

SENSITIVE_PATTERNS=(
  "api_key"
  "secret"
  "password"
  "token"
  "private key"
  "BEGIN RSA"
  "BEGIN OPENSSH"
)

exit_code=0

###############################################################################
# Utility
###############################################################################
print_banner() {
  echo "========================================"
  echo "  OpenHands Quality Gate"
  echo "========================================"
}

print_section() {
  echo ""
  echo "--- $1 ---"
}

###############################################################################
# 1. Git status overview
###############################################################################
print_section "Git Status (short)"
git status --short 2>/dev/null || echo "(not a git repository or git not available)"

###############################################################################
# 2. Check for modified forbidden files
###############################################################################
print_section "Checking forbidden file modifications"

changed_files=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  changed_files=$(git diff --name-only --cached; git diff --name-only)
fi

if [ -z "$changed_files" ]; then
  echo "✓ No staged or unstaged changes detected."
else
  for pattern in "${FORBIDDEN_FILE_PATTERNS[@]}"; do
    while IFS= read -r match; do
      if [ -n "$match" ]; then
        echo "✗ FORBIDDEN: Matched pattern '$pattern' — $match"
        exit_code=1
      fi
    done < <(echo "$changed_files" | grep -i "$pattern" || true)
  done
fi

if [ "$exit_code" -eq 0 ]; then
  echo "✓ No forbidden files modified."
fi

###############################################################################
# 3. Scan git diff for sensitive content
###############################################################################
print_section "Scanning for sensitive content in diff"

diff_content=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  diff_content=$(git diff --cached; git diff)
fi

found_sensitive=false
if [ -n "$diff_content" ]; then
  for pattern in "${SENSITIVE_PATTERNS[@]}"; do
    if echo "$diff_content" | grep -iq "$pattern"; then
      echo "✗ SENSITIVE: Diff contains pattern '$pattern'"
      found_sensitive=true
      exit_code=1
    fi
  done
fi

if [ "$found_sensitive" = false ]; then
  echo "✓ No sensitive content detected in diff."
fi

###############################################################################
# 4. Run project tests if applicable
###############################################################################
print_section "Running project tests"

# Python project — check if pytest is available
if [ -f "pyproject.toml" ] || [ -f "setup.py" ] || [ -f "requirements.txt" ]; then
  if command -v pytest >/dev/null 2>&1; then
    echo "→ Python project detected, running pytest -q ..."
    if pytest -q; then
      echo "✓ pytest passed."
    else
      echo "✗ pytest failed."
      exit_code=1
    fi
  else
    echo "→ Python project detected but pytest is not available — skipping."
  fi
fi

# Node project — check if npm test is available
if [ -f "package.json" ]; then
  if command -v npm >/dev/null 2>&1; then
    if npm test; then
      echo "✓ npm test passed."
    else
      echo "✗ npm test failed."
      exit_code=1
    fi
  else
    echo "→ Node project detected but npm is not available — skipping."
  fi
fi

###############################################################################
# 5. Summary
###############################################################################
print_section "Quality Gate Summary"
if [ "$exit_code" -eq 0 ]; then
  echo "✓ All checks passed."
else
  echo "✗ One or more checks failed — review the issues above."
fi

exit "$exit_code"
